name: Matrix Demo
on:
  push:
    branches:
      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 20
            os: ubuntu-latest
        exclude:
          - node-version: 14
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependcies
        run: npm install
      - name: build app
        run: npm run build
