name: Reusable Deploy
on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      artifact-name:
        description: the name of deplyed artifacts files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: output info
        run: echo "deply sucess"
