name: Env App Section 6
on:
  push:
    branches:
      - "main"
      - "dev-*" # dev-new or dev-is-new and so on
      - "feat/**" # feat/new feat/new/button
env:
  VITE_BASE_APP_NAME: GITHUB_CI_CD_COURSE
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # - name: Use Node.js 20
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
        # - name: Use Node.js 20
        #   uses: actions/setup-node@v4
        # with:
        #   node-version: "20"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Publish JS File Name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output build artifacts
        run: ls
      - name: output file name
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying... App Title =>,$VITE_BASE_APP_NAME , or , ${{env.VITE_BASE_APP_NAME}}"
